<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Facturadora extends Model
{
    protected $table = 'master_empresa';
    protected $primaryKey = 'IdEmpresa';
    protected $fillable = [
      'IdEmpresa',
      'Codigo',
      'FK_Titulo',
      'RazonSocial',
      'RepresentanteLegal',
      'Descripcion',
      'Rfc',
      'RegimenFiscal',
      'RegPatronal',
      'Calle',
      'NoInt',
      'NoExt',
       'Colonia',
       'CP',
       'IdPais',
       'IdPadre',
        'IdEstado',
        'IdCiudad',
        'Localidad',
        'Slogan',
        'Certificado',
        'ArchivoCert',
        'Llave',
        'ArchivoKey',
        'ClaveCSD',
        'CorreoElectronico',
        'Web',
        'Fax',
        'Telefono',
        'Logotipo',
        'Cedula',
        'Contrasena',
        'ArchivosEmpresa',
        'Decimales',
        'MascaraCliente',
        'MascaraProveedores',
        'Iva',
        'IESPS',
        'TipoIESPS',
        'RetencionISR',
        'RetencionIVA',
        'Activo',
        'IdGiro',
        'IdMoneda',
        'UtilidadBase',
        'UtilidadMinima',
        'IdDepartamento',
        'IdRegimenFiscal',
        'RFCRepresentante',
        'CURPRepresentante',
        'IdOrigenRecurso',
        'created_at',
        'updated_at',
        'FormaJuridica',
        'IdActividadEconomica',
        'pf_nombre',
        'pf_apellido_paterno',
        'pf_apellido_materno',
        'pf_lugar_nacimiento',
        'pf_genero',
        'pf_fecha_nacimiento',
        'fecha_constitucion',
        'fecha_inicio_operaciones',
        'fecha_registro_mercantil',
        'pf_CURP',
        'clase_pm',
        'correo_representante',
        'telefono_representante',
        'municipio',
        'id_user',
        'facturadorascol',
        'facturadorascol1',
        'TipoEmpresa',
        'Calle_dc',
        'NoInt_dc',
        'NoExt_dc',
        'Colonia_dc',
        'CP_dc',
        'IdPais_dc',
        'IdEstado_dc',
        'IdCiudad_dc',
        'Municipio_dc',
        'clase_rt',
        'DeptW',
        'NoContratoDispersion'
    ];
}
